# Config file for lsf cluster

# Configuration file version (do not change)
config_version: 5

# cluster command for lsf
cluster_cores: 10000
cluster_nodes: 500
cluster_cmd: "bsub -q {cluster.queue} -n {cluster.threads} -M {cluster.mem} -J {cluster.name} -oo {cluster.output} -eo {cluster.error}"

# DEFAULT CLUSTER OPTIONS
__default__:
    threads: 2
    mem: 5000
    queue: "research-rh74"
    name : "nanosnake_DNA_ONT.{rule}.{wildcards.sample}"
    output : "logs/{rule}/{wildcards.sample}_bsub_stdout.log"
    error : "logs/{rule}/{wildcards.sample}_bsub_stderr.log"

# MAIN RULES
preprocess_genone:
    opt: ""
    name : "nanosnake_DNA_ONT.{rule}"
    output : "logs/{rule}/bsub_stdout.log"
    error : "logs/{rule}/bsub_stderr.log"

pbt_fastq_filter:
    opt: "--remove_duplicates --min_len 100 --min_qual 7"

minimap2_index:
    opt: ""
    mem : 20000
    name : "nanosnake_DNA_ONT.{rule}"
    output : "logs/{rule}/bsub_stdout.log"
    error : "logs/{rule}/bsub_stderr.log"

minimap2_align:
    opt: "-x map-ont -L"
    threads : 40
    mem : 40000

pbt_alignment_filter:
    opt: "--min_align_len 100 --min_freq_identity 0.7 --skip_unmapped --skip_secondary --skip_supplementary"

# OPTIONAL DNA METHYLATION RULES, can be commented to be skippe
nanopolish_index:
    opt: ""
    mem: 10000

nanopolish_call_methylation:
    opt: "--methylation cpg"
    threads: 40
    mem: 10000

pycometh_cgi_finder:
    opt: ""
    name : "nanosnake_DNA_ONT.{rule}"
    output : "logs/{rule}/bsub_stdout.log"
    error : "logs/{rule}/bsub_stderr.log"

pycometh_cpg_aggregate:
    opt: "--min_depth 10"
    mem: 50000

pycometh_interval_aggregate:
    opt: "--min_cpg_per_interval 5"
    mem: 10000

pycometh_meth_comp:
    opt: "--max_missing 1"
    mem: 10000
    name : "nanosnake_DNA_ONT.{rule}"
    output : "logs/{rule}/bsub_stdout.log"
    error : "logs/{rule}/bsub_stderr.log"

# OPTIONAL STRUCTURAL VARIANT RULES, can be commented to be skipped
ngmlr:
    opt: "-x ont"
    threads: 40
    mem: 50000

sniffles:
    opt: "--min_support 10 --max_num_splits 7 --max_distance 1000 --min_length 30 --minmapping_qual 10"
    threads: 5
    mem: 10000

# pycosv_filter_variants:
#     opt: ""
#
# pycosv_varcomp:
#     opt: ""

# OPTIONAL QC RULES, can be commented to be skipped
pycoqc:
    opt: "--filter_calibration --filter_duplicated --min_pass_len 100 --min_pass_qual 7"
    mem: 20000

samtools_qc:
    opt: ""
    mem: 10000

# OPTIONAL COVERAGE RULES, can be commented to be skipped
bedtools_genomecov:
    opt: "-bg"
    mem: 20000

igvtools_count:
    opt: "-w 10"
    mem: 20000
