# All the rules accept the following parameters: opt, threads, mem

# Configuration file version (do not change)
config_version: 3

# MAIN RULES
preprocess_genone:
    opt: ""

pbt_fastq_filter:
    opt: "--remove_duplicates --min_len 100 --min_qual 7"

minimap2_index:
    opt: ""

minimap2_align:
    opt: "-x map-ont -L"
    threads: 4

pbt_alignment_filter:
    opt: "--min_align_len 100 --min_freq_identity 0.7 --skip_unmapped --skip_secondary --skip_supplementary"

# OPTIONAL DNA METHYLATION RULES, can be commented to be skipped
nanopolish_index:
    opt: ""

nanopolish_call_methylation:
    opt: "--methylation cpg"
    threads: 4

pycometh_cpg_aggregate:
    opt: "--min_depth 10"

# pycometh_cpg_methcomp:
#     opt: ""
#
# pycometh_interval_aggregate:
#     opt: ""
#
# pycometh_interval_methcomp:
#     opt: ""

# OPTIONAL STRUCTURAL VARIANT RULES, can be commented to be skipped
ngmlr:
    opt: "-x ont"
    threads: 4

sniffles:
    opt: "--min_support 10 --max_num_splits 7 --max_distance 1000 --min_length 30 --minmapping_qual 10"

# pycosv_filter_variants:
#     opt: ""
#
# pycosv_varcomp:
#     opt: ""

# OPTIONAL QC RULES, can be commented to be skipped
pycoqc:
    opt: "--filter_calibration --filter_duplicated --min_pass_len 100 --min_pass_qual 7"

samtools_qc:
    opt: ""

# OPTIONAL COVERAGE RULES, can be commented to be skipped
bedtools_genomecov:
    opt: "-bg"

igvtools_count:
    opt: "-w 10"
