# Config file for lsf cluster

__default__:
    queue: "research-rh74"
    name : "nanosnake.{rule}.{wildcards.sample}"
    output : "logs/{rule}/{wildcards.sample}_bsub_stdout.log"
    error : "logs/{rule}/{wildcards.sample}_bsub_stderr.log"

merge_filter_fastq:
    opt: "--min_len 100 --remove_duplicates"
    threads : 2
    mem : 5000

fastqc:
    opt: ""
    threads: 10
    mem : 5000

minimap2_index:
    opt: ""
    threads : 2
    mem : 20000
    name : "nanosnake.{rule}"
    output : "logs/{rule}/bsub_stdout.log"
    error : "logs/{rule}/bsub_stderr.log"

minimap2_align:
    opt: "-x map-ont"
    threads : 20
    mem : 40000

bamqc:
    opt: ""
    threads : 2
    mem: 50000

samtools_filter:
    opt: "-q 10 -F 3844"
    threads : 20
    mem : 20000

genomecov:
    opt: "-bg"
    threads : 2
    mem: 20000
