# snakemake general config file

merge_filter_fastq:
    opt: "--min_len 100 --remove_duplicates"
    threads: 1
    mem: 1000

fastqc:
    opt: ""
    threads: 2
    mem: 1000

minimap2_index:
    opt: ""
    threads: 1
    mem: 1000

minimap2_align:
    opt: "-x map-ont"
    threads: 4
    mem: 1000

bamqc:
    opt: ""
    threads: 1
    mem: 1000

samtools_filter:
    opt: "-q 10 -F 3844"
    threads: 4
    mem: 1000

genomecov:
    opt: "-bg"
    threads: 1
    mem: 1000
