# snakemake general cluster config file


merge_fastq:
    opt: ""
    outdir: "01_merge_fastq"

fastqc:
    opt: ""
    threads: 2
    outdir: "02_fastQC"

minimap2_index:
    opt: ""
    outdir: "03_minimap2_index"

minimap2_align:
    opt: "-x map-ont"
    threads: 4
    outdir: "04_minimap2_align"

bamqc:
    opt: ""
    outdir: "05_bamqc"

samtools_filter:
    opt: "-q 10 -F 3844"
    threads: 4
    outdir: "06_samtools_filter"

genomecov:
    opt: "-bg"
    outdir: "07_genomecov"
