# Fastq options
merge_fastq:
    opt: ""
    threads: 2
    outdir: "01_merge_fastq"

# FastQC options
fastqc:
    opt: ""
    threads: 2
    outdir: "02_fastQC"

# Genome indexing
minimap2_index:
    opt: ""
    threads: 2
    outdir: "03_minimap2_index"

# Alignment
minimap2_align:
    opt: "-x map-ont"
    threads: 4
    outdir: "04_minimap2_align"

# QC with qualimap + samtools stats flagstat and idxstat
bamqc:
    opt: ""
    threads: 2
    outdir: "05_bamqc"

# Bam filtering with samtools view + sort and index
samtools_filter:
    opt: "-q 10 -F 3844"
    threads: 4
    outdir: "06_samtools_filter"

# Bam filtering with samtools view + sort and index
genomecov:
    opt: "-bg"
    outdir: "07_genomecov"
