dist: xenial
language: python
python: 3.6
branches:
  only:
  - master
  - dev

install: skip
script: skip

deploy:
  # Deploy to Anaconda
  - provider: script
    skip_cleanup: true
    script: bash ./deploy_anaconda.sh $ANACONDA_TOKEN
    on:
      branch: master

  # Deploy to Anaconda
  - provider: script
    skip_cleanup: true
    script: bash ./deploy_anaconda.sh $ANACONDA_DEV_TOKEN
    on:
      branch: dev
