dist: xenial
language: python
python: 3.6
branches:
  only:
  - master

install: skip
script: skip

deploy:
  # Deploy to Anaconda
  - provider: script
    skip_cleanup: true
    script: bash ./deploy_anaconda.sh
    on:
      branch: master
