# Config file for lsf cluster

# DEFAULT OPTIONS

__default__:
    queue: "research-rh74"
    name : "nanosnake.{rule}.{wildcards.sample}"
    output : "logs/{rule}/{wildcards.sample}_bsub_stdout.log"
    error : "logs/{rule}/{wildcards.sample}_bsub_stderr.log"

# MAIN PIPELINE CONFIG
# These rules are the backbone of the pipeline

merge_filter_fastq:
    opt: "--min_len 100 --remove_duplicates"
    threads: 2
    mem: 5000

minimap2_index:
    opt: ""
    threads : 2
    mem : 20000
    name : "nanosnake.{rule}"
    output : "logs/{rule}/bsub_stdout.log"
    error : "logs/{rule}/bsub_stderr.log"

minimap2_align:
    opt: "-x map-ont"
    threads : 20
    mem : 40000

samtools_filter:
    opt: "-q 10 -F 3844"
    threads : 20
    mem : 20000

nanopolish_index:
    opt: ""
    threads: 2
    mem: 10000

nanopolish_call_methylation:
    opt: "--methylation cpg"
    threads: 20
    mem: 10000

nanopolishcomp_freq_meth_calculate:
    opt: "--min_depth 20"
    threads: 2
    mem: 50000

# OPTIONAL PIPELINE CONFIG
# Removing a rule block will cause the rule not to be triggered

pycoqc:
    opt: "--filter_calibration"
    threads: 2
    mem: 10000

samtools_qc:
    threads: 1
    mem: 10000

genomecov:
    opt: "-bg"
    threads : 2
    mem: 20000

igvtools_count:
    opt: "-w 10"
    threads: 1
    mem: 20000
