title: "Nanopore CpG methylation analysis"
intro_text: "MultiQC reports summarise analysis results"

report_header_info:
    - Contact E-mail: 'aleg@ebi.ac.uk'
    - Project Type: 'CpG methylation analysis'
    - Sequencing Platform: 'ONT Promethion'
    - Sequencing Setup: 'Ligation kit, standard library preparation '

read_count_multiplier: 0.001
read_count_prefix: 'K'
read_count_desc: 'thousands'

module_order:
    - fastqc
    - samtools
    - qualimap

sp:
    fastqc/zip:
        - fn: '*_fastqc.zip'
        - shared: true
    samtools/stats:
        - fn: '*_samtools_stats.txt'
        - shared: true
    samtools/flagstat:
        - fn: '*_samtools_flagstat.txt'
        - shared: true
    samtools/idxstats:
        - fn: '*_samtools_idxstats.txt'
        - shared: true

extra_fn_clean_exts:
    - '_fastqc.zip'
    - '_samtools_stats.txt'
    - '_samtools_flagstat.txt'
    - '_samtools_idxstats.txt'
