# Config file for lsf cluster
# Optional rules can be commented to be skipped
# Example command line for LSF:
# bsub NanoSnake DNA -r ref.fa -s sample_sheet.tsv -c cluster_config.yaml --cores 1000 --nodes 10 \
# --cluster "bsub -q {cluster.queue} -n {cluster.threads} -M {cluster.mem} \
# -R \"select[mem>{cluster.mem}] rusage[mem={cluster.mem}] span[hosts=1]\" -J {cluster.name} -oo {cluster.output} -eo {cluster.error}"

# DEFAULT OPTIONS
__default__:
    queue: "research-rh74"
    name : "nanosnake.{rule}.{wildcards.sample}"
    output : "logs/{rule}/{wildcards.sample}_bsub_stdout.log"
    error : "logs/{rule}/{wildcards.sample}_bsub_stderr.log"

# REQUIRED CORE RULES
merge_filter_fastq:
    opt: "--min_len 100 --remove_duplicates --min_qual 5"
    threads: 2
    mem: 5000

minimap2_index:
    opt: ""
    threads : 2
    mem : 20000
    name : "nanosnake.{rule}"
    output : "logs/{rule}/bsub_stdout.log"
    error : "logs/{rule}/bsub_stderr.log"

minimap2_align:
    opt: "-x map-ont --MD -L"
    threads : 40
    mem : 40000

samtools_filter:
    opt: "-q 10 -F 3844"
    threads : 20
    mem : 20000

# OPTIONAL DNA METHYLATION RULES
nanopolish_index:
    opt: ""
    threads: 2
    mem: 10000

nanopolish_call_methylation:
    opt: "--methylation cpg"
    threads: 40
    mem: 10000

pycometh_aggregate:
    opt: "--min_depth 10"
    threads: 2
    mem: 50000

# OPTIONAL STRUCTURAL VARIANT RULES
sniffles:
    opt: "--min_support 10 --max_num_splits 7 --max_distance 1000 --min_length 30 --minmapping_qual 10"
    threads: 5
    mem: 10000

# OPTIONAL QC RULES
pycoqc:
    opt: "--filter_calibration"
    threads: 2
    mem: 10000

samtools_qc:
    threads: 1
    mem: 10000

# OPTIONAL COVERAGE RULES
genomecov:
    opt: "-bg"
    threads : 2
    mem: 20000

igvtools_count:
    opt: "-w 10"
    threads: 1
    mem: 20000
