# Optional rules can be commented to be skipped

# REQUIRED CORE RULES
merge_filter_fastq:
    opt: "--min_len 100 --remove_duplicates --min_qual 5"
    threads: 1
    mem: 1000

minimap2_index:
    opt: ""
    threads: 1
    mem: 1000

minimap2_align:
    opt: "-x map-ont --MD -L"
    threads: 4
    mem: 1000

samtools_filter:
    opt: "-q 10 -F 3844"
    threads: 4
    mem: 1000

# OPTIONAL DNA METHYLATION RULES
nanopolish_index:
    opt: ""
    threads: 1
    mem: 1000

nanopolish_call_methylation:
    opt: "--methylation cpg"
    threads: 4
    mem: 1000

pycometh_aggregate:
    opt: "--min_depth 10"
    threads: 1
    mem: 1000

# OPTIONAL STRUCTURAL VARIANT RULES
sniffles:
    opt: "--min_support 10 --max_num_splits 7 --max_distance 1000 --min_length 30 --minmapping_qual 10"
    threads: 1
    mem: 1000

# OPTIONAL QC RULES
pycoqc:
    opt: "--filter_calibration"
    threads: 2
    mem: 1000

samtools_qc:
    threads: 1
    mem: 1000

# OPTIONAL COVERAGE RULES
genomecov:
    opt: "-bg"
    threads: 1
    mem: 1000

igvtools_count:
    opt: "-w 10"
    threads: 1
    mem: 1000
