# Config file for lsf cluster

# Configuration file version (do not change)
config_version: 3

# cluster command for lsf
cluster_cores: 10000
cluster_nodes: 500
cluster_cmd: "bsub -q {cluster.queue} -n {cluster.threads} -M {cluster.mem} -J {cluster.name} -oo {cluster.output} -eo {cluster.error}"

# DEFAULT CLUSTER OPTIONS
__default__:
    threads: 2
    mem: 5000
    queue: "research-rh74"
    name : "nanosnake_RNA_illumina.{rule}.{wildcards.sample}"
    output : "logs/{rule}/{wildcards.sample}_bsub_stdout.log"
    error : "logs/{rule}/{wildcards.sample}_bsub_stderr.log"

# MAIN RULES
preprocess_genone:
    name : "nanosnake_RNA_illumina.{rule}"
    output : "logs/{rule}/bsub_stdout.log"
    error : "logs/{rule}/bsub_stderr.log"
    opt: ""

preprocess_annotation:
    name : "nanosnake_RNA_illumina.{rule}"
    output : "logs/{rule}/bsub_stdout.log"
    error : "logs/{rule}/bsub_stderr.log"
    opt: "--keep-exon-attrs --keep-genes"

fastp:
    opt: ""
    threads: 20
    mem: 10000

star_index:
    name : "nanosnake_RNA_illumina.{rule}"
    output : "logs/{rule}/bsub_stdout.log"
    error : "logs/{rule}/bsub_stderr.log"
    opt: ""
    threads: 20
    mem: 50000

star_align:
    opt: "--outFilterType BySJout  --outFilterMultimapNmax 20 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --outFilterMismatchNmax 999 --outFilterMismatchNoverLmax 0.04 --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000"
    threads: 20
    mem: 20000

pbt_alignment_filter:
    opt: "--min_align_len 50 --min_freq_identity 0.7 --skip_unmapped --skip_secondary --skip_supplementary"

star_count_merge:
    opt: ""
    mem: 20000
    name : "nanosnake_RNA_illumina.{rule}"
    output : "logs/{rule}/bsub_stdout.log"
    error : "logs/{rule}/bsub_stderr.log"

# OPTIONAL RULES (comment to be skiped)
# cufflinks:
#     opt: "--library-type fr-firststrand --upper-quartile-norm"
#     threads: 20
#     mem: 20000

# cufflinks_fpkm_merge:
#     opt: ""
#     mem: 20000
#     name : "nanosnake_RNA_illumina.{rule}"
#     output : "logs/{rule}/bsub_stdout.log"
#     error : "logs/{rule}/bsub_stderr.log"

subread_featurecounts:
    opt: "-p"
    threads: 20
    mem: 20000

subread_featurecounts_merge:
    opt: ""
    mem: 20000

samtools_qc:
    opt: ""
    mem: 10000

bedtools_genomecov:
    opt: "-bg"
    mem: 20000

igvtools_count:
    opt: "-w 10"
    mem: 20000
