package:
  name: NanoSnake
  version: 0.0.0.a1

source:
  path: ../

build:
  number: 0
  noarch: python
  skip: True

requirements:
  build:
    - python=3.6
  run:
    - python=3.6
    - snakemake>=5.4.2
    - pandas>=0.24.1
    - graphviz

about:
  home: "https://github.com/a-slide/NanoSnake"
  license: MIT
  summary: 
