# Required input files and dirs
sample_sheet: ""
reference: ""

# Default directories
envs_dir: "../envs/"
scripts_dir: "../scripts/"
rules_dir: "../rules/"

# FastqQC options
fastqc:
    cmd_opt: ""
    outdir: "01_fastqc"

# Alignment
align:
    minimap2_opt: "-ax map-ont"
    samtools_opt: ""
    outdir: "02_align"

# Nanopolish
nanopolish:
    nanopolish_index_opt: ""
    outdir: "03_nanopolish"
