# Fastq options
merge_fastq:
    outdir: "01_merge_fastq"

# FastQC options
fastQC:
    opt: ""
    threads: 2
    outdir: "02_fastQC"

# Alignment
minimap2_index:
    opt: ""
    threads: 2
    outdir: "03_minimap2_index"

# Alignment
minimap2_align:
    opt: "-x map-ont"
    threads: 2
    outdir: "04_minimap2_align"

# Samtools_stats
samtools_qc:
    outdir: "05_samtools_stats"

# samtools_view_opt: "-q 10 -F 3844"
