# Fastq options
merge_fastq:
    outdir: "01_merge_fastq"

# FastQC options
fastQC:
    params: "--nano"
    outdir: "02_fastQC"

# Alignment
minimap2_index:
    params: ""
    outdir: "03_minimap2_index"

# Alignment
minimap2_align:
    params: "-ax map-ont"
    outdir: "04_minimap2_align"

# Samtools_stats
samtools_stats:
    params: ""
    outdir: "05_samtools_stats"
